spring:
  #  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5401/db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true